name: Build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure build
      run: cmake -B build .
    - name: Build
      run: cmake --build build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup clang-tidy
        run: sudo apt-get install clang-tidy
      - name: Configure build
        run: cmake -B config -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Lint with clang-tidy
        run: find src include -name *.c -o -name *.h | xargs -i clang-tidy {} -p config --Iinclude
